### ISSUE TITLE
app is not installable

### ISSUE THREAD

**Issue by hdid** [lparam/xTun-android#1]
when i want to install this app i get error:

![screenshot](https://cloud.githubusercontent.com/assets/3944323/15807582/2ef48306-2b77-11e6-8ef2-56e90a79b7b0.png)

Android is v4.2.2

**Comment by lparam** [comment]
What's your device brand for?
Try v4.3 or above version.

**Comment by hdid** [comment]
@lparam  It's Huawei Honor 4X. Can you rebuild it for lower android version?
Thanks

**Comment by hdid** [comment]
@lparam  It's Huawei. Can you rebuild it for lower android version?
Thanks

**Comment by lparam** [comment]
No plan for this.
